### ISSUE TITLE
New Picker more complicated?

### ISSUE THREAD

**Issue by IschaGast** [ThePacielloGroup/CCA-OSX#30]
I am a big fan of the Colour Contrast Analyzer but with the new version I have to click multiple times to get the real picker and in the old version I just had to click picker and there it was.

Am I doing something wrong or is this on purpose?

![image](https://user-images.githubusercontent.com/39517/31488742-050b53d8-af3f-11e7-8c90-1ac09a2816fd.png)

Screen recording new version:
[new.zip](https://github.com/ThePacielloGroup/CCA-OSX/files/1378767/new.zip)

Screen recording old version:
[old.zip](https://github.com/ThePacielloGroup/CCA-OSX/files/1378780/old.zip)

**Comment by ferllings** [comment]
Hi IschaGast,

Yes, this is on purpose, but temporary, for 2 reasons:
1. I have a problem, with the previous picker, which doesn't capture the correct Colour Space, then doesn't get the correct colour value on some cases.
2. The current colour panel has asked by few people because it has additional conversion features (https://github.com/ThePacielloGroup/CCA-OSX/issues/26)

So my plan is to figure-out the issue with the previous picker and reintroduce it in the next release.
